export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCAGRA_PRODUCTOS_EXITO = "DESCAGRA_PRODUCTOS_EXITO";
export const DESCAGRA_PRODUCTOS_ERROR = "DESCAGRA_PRODUCTOS_ERROR";
